### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by OzamaDz** [BeepFelix/CSGO---Discord-RichEmbed#36]
use my version, I fixed it, and I'll update it for long time.

**Comment by Coder-bots** [comment]
siyylna video mn3rfch ndir Installation : /

**Comment by OzamaDz** [comment]
> siyylna video mn3rfch ndir Installation : /

Discord: Ozama#8188

**Comment by XdekHckr** [comment]
> > siyylna video mn3rfch ndir Installation : /
> 
> Discord: Ozama#8188

your version doesn't work, after typing "npm install" it throws errors and node modules folder is empty...

**Comment by XdekHckr** [comment]
> > siyylna video mn3rfch ndir Installation : /
> 
> Discord: Ozama#8188

Please look at this
![image](https://user-images.githubusercontent.com/43490312/207114622-f0555281-8b16-4b9b-adec-1d1c64bd9cc4.png)


```cmd
PS D:\Desktop\dokumenty\MEDIA\SOFTWARE\SCRIPTS\CSGO-RPC-master v2> npm install
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\xdekh\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > register-scheme@0.0.2 install
npm ERR! > node-gyp rebuild
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.2.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.1 found at "C:\Users\xdekh\AppData\Local\Programs\Python\Python311\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2015 (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:353:14)
npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:67:12
npm ERR! gyp ERR! stack     at failPowershell (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:156:7)
npm ERR! gyp ERR! stack     at VisualStudioFinder.parseData (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:170:14)
npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:143:14
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:411:7)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xdekh\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\xdekh\AppData\Local\npm-cache\_cacache\tmp\git-cloneAnO6AS
npm ERR! gyp ERR! node -v v19.2.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\xdekh\AppData\Local\npm-cache\_cacache\tmp\git-cloneAnO6AS
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\xdekh\AppData\Local\npm-cache\_logs\2022-12-12T17_36_47_816Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xdekh\AppData\Local\npm-cache\_logs\2022-12-12T17_36_46_261Z-debug-0.log```

**Comment by JunWeiLi233** [comment]
> > > siyylna video mn3rfch ndir Installation : /
> > 
> > 
> > Discord: Ozama#8188
> 
> Please look at this ![image](https://user-images.githubusercontent.com/43490312/207114622-f0555281-8b16-4b9b-adec-1d1c64bd9cc4.png)
> 
> ```batchfile
> PS D:\Desktop\dokumenty\MEDIA\SOFTWARE\SCRIPTS\CSGO-RPC-master v2> npm install
> npm ERR! code 1
> npm ERR! git dep preparation failed
> npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\xdekh\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
> npm ERR! > register-scheme@0.0.2 install
> npm ERR! > node-gyp rebuild
> npm ERR! npm WARN using --force Recommended protections disabled.
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.3.0
> npm ERR! gyp info using node@19.2.0 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.11.1 found at "C:\Users\xdekh\AppData\Local\Programs\Python\Python311\python.exe"
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
> npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
> npm ERR! gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
> npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> npm ERR! gyp ERR! find VS For more information consult the documentation at:
> npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
> npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
> npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
> npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
> npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2015 (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:353:14)
> npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:67:12
> npm ERR! gyp ERR! stack     at failPowershell (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:156:7)
> npm ERR! gyp ERR! stack     at VisualStudioFinder.parseData (C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:170:14)
> npm ERR! gyp ERR! stack     at C:\Users\xdekh\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:143:14
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:411:7)
> npm ERR! gyp ERR! System Windows_NT 10.0.22621
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xdekh\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd C:\Users\xdekh\AppData\Local\npm-cache\_cacache\tmp\git-cloneAnO6AS
> npm ERR! gyp ERR! node -v v19.2.0
> npm ERR! gyp ERR! node-gyp -v v9.3.0
> npm ERR! gyp ERR! not ok
> npm ERR! npm ERR! code 1
> npm ERR! npm ERR! path C:\Users\xdekh\AppData\Local\npm-cache\_cacache\tmp\git-cloneAnO6AS
> npm ERR! npm ERR! command failed
> npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
> npm ERR!
> npm ERR! npm ERR! A complete log of this run can be found in:
> npm ERR! npm ERR!     C:\Users\xdekh\AppData\Local\npm-cache\_logs\2022-12-12T17_36_47_816Z-debug-0.log
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xdekh\AppData\Local\npm-cache\_logs\2022-12-12T17_36_46_261Z-debug-0.log```
> ```

just install visual studio with c++ desket then u solved that.
